/* Day 5 Countries Array
export const countries = [
  "Albania",
  "Bolivia",
  "Canada",
  "Denmark",
  "Ethiopia",
  "Finland",
  "Germany",
  "Hungary",
  "Ireland",
  "Japan",
  "Kenya",
];
*/
export const webTechs = [
  "HTML",
  "CSS",
  "JavaScript",
  "React",
  "Redux",
  "Node",
  "MongoDB",
];
export const countries = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Cape Verde",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Colombi",
  "Comoros",
  "Congo (Brazzaville)",
  "Congo",
  "Costa Rica",
  "Cote d'Ivoire",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czech Republic",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "East Timor (Timor Timur)",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "Gambia, The",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Korea, North",
  "Korea, South",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Macedonia",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia and Montenegro",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Swaziland",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Togo",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Vatican City",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe",
];
export const colorsHex = [
  "#ff0000",
  "#0000ff",
  "#00ff00",
  "#ffff00",
  "#ffa500",
  "#800080",
  "#ffc0cb",
  "#00ffff",
  "#ff00ff",
  "#008080",
  "#00ff00",
  "#800000",
  "#000080",
  "#808000",
  "#c0c0c0",
  "#ffffff",
  "#a52a2a",
  "#808080",
  "#4b0082",
  "#40e0d0",
  "#fa8072",
  "#87ceeb",
  "#ee82ee",
  "#ff7f50",
  "#da70d6",
  "#ffd700",
  "#f0e68c",
  "#fffff0",
  "#d2b48c",
  "#dc143c",
  "#7fffd4",
  "#e6e6fa",
  "#dda0dd",
  "#7fff00",
  "#ff6347",
  "#faf0e6",
  "#cd853f",
  "#d8bfd8",
  "#6495ed",
  "#b22222",
  "#2f4f4f",
  "#bdb76b",
  // Add more colors as needed
];
export const monthNames = [
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December",
];
export const ayKeywords = [
  "#HTML",
  "#HTML5",
  "#CSS",
  "#CSS",
  "#JS",
  "#JavaScript",
  "#ES6",
  "#Promise",
  "#async await",
  "#Database",
  "#React",
  "#React Hooks",
  "#Context API",
  "#React Router",
  "#Redux",
  "#Node",
  "#MongoDB",
  "#SQL",
  "#API",
  "#DOM",
  "#data science",
  "#MERN",
  "#Python",
  "#Flask",
  "#Statistics",
  "#Linear Algebra",
  "#Numpy",
  "#Pandas",
  "#Scipy",
  "#Scikit-learn",
  "#Visualization",
  "#D3.js",
];
export const aySkills = [
  { value: "Web Development", path: "../icon/tick.png" },
  { value: "Data Analysis", path: "../icon/tick.png" },
  { value: "Data Visualization", path: "../icon/tick.png" },
  { value: "Programming", path: "../icon/tick.png" },
  { value: "Databases", path: "../icon/tick.png" },
  { value: "Developing API", path: "../icon/tick.png" },
];
export const ayQualifications = [
  { value: "MSc. Computer Science Ongoing", path: "../icon/book.png" },
  {
    value: "Bsc. Information and Communication Eng.",
    path: "../icon/graduate.png",
  },
  { value: "MSc. Food Technology", path: "../icon/graduate.png" },
  { value: "BSc. Food Technology", path: "../icon/graduate.png" },
];
export const ayTitles = [
  { value: "Educator", path: "../icon/plant.png" },
  { value: "Programmer", path: "../icon/laptop.png" },
  { value: "Developer", path: "../icon/globe.png" },
  { value: "Motivator", path: "../icon/fire.png" },
  { value: "Content Creator", path: "../icon/contentCreator.png" },
];
export const skillData = [
  {
    course: "30 Days of Python",
    lang: "Pyhton",
    summary: ["Numpy", "Skit Learn", "Pandas", "dictionary"],
    type: "Done",
  },
  {
    course: "30 Days of JavaScript",
    lang: "JavaScript",
    summary: ["JS", "React", "Next,js", "Node", "MongoDB", "Django"],
    type: "Ongoing",
  },
  {
    course: "30 Days of HTML & CSS",
    lang: "HTML & CSS",
    summary: ["HTML", "CSS", "Bootstrap", "XML", "SCSS"],
    type: "Coming",
  },
  {
    course: "30 Days of React",
    lang: "React",
    summary: ["React", "ReactNative", "Next.js", "JavaScript"],
    type: "Coming",
  },
  {
    course: "30 Days of ReactNative",
    lang: "ReactNative",
    summary: ["JavaScript", "Java", "C++", "Objective - C", "Python"],
    type: "Coming",
  },
  {
    course: "30 Days of Fullstack",
    lang: "Fullstack",
    summary: ["MongoDB", "Express.js", "Node JS", "React"],
    type: "Coming",
  },
  {
    course: "30 Days of Data Analysis",
    lang: "Data Analysis",
    summary: [
      "Tableau",
      "Data Visualization",
      "R",
      "SAS",
      "Machine Learning",
      "Python",
      "Apache Hadoop",
    ],
    type: "Coming",
  },
  {
    course: "30 Days of Machine Learning",
    lang: "Machine Learning",
    summary: ["AI", "Gen AI", "Robotics"],
    type: "Coming",
  },
];

export const keyCodes = {
  8: "Backspace",
  9: "Tab",
  13: "Enter",
  16: "Shift",
  17: "Control",
  18: "Alt",
  20: "Caps Lock",
  27: "Escape",
  32: "Space bar",
  33: "Page Up",
  34: "Page Down",
  35: "End",
  36: "Home",
  37: "Arrow Left",
  38: "Arrow Up",
  39: "Arrow Right",
  40: "Arrow Down",
  45: "Insert",
  46: "Delete",
  48: "0",
  49: "1",
  50: "2",
  51: "3",
  52: "4",
  53: "5",
  54: "6",
  55: "7",
  56: "8",
  57: "9",
  65: "A",
  66: "B",
  67: "C",
  68: "D",
  69: "E",
  70: "F",
  71: "G",
  72: "H",
  73: "I",
  74: "J",
  75: "K",
  76: "L",
  77: "M",
  78: "N",
  79: "O",
  80: "P",
  81: "Q",
  82: "R",
  83: "S",
  84: "T",
  85: "U",
  86: "V",
  87: "W",
  88: "X",
  89: "Y",
  90: "Z",
  91: "Left Window",
  92: "Right Window",
  93: "Select",
  106: "*",
  107: "+",
  109: "-",
  110: ".",
  111: "/",
  112: "F1",
  113: "F2",
  114: "F3",
  115: "F4",
  116: "F5",
  117: "F6",
  118: "F7",
  119: "F8",
  120: "F9",
  121: "F10",
  122: "F11",
  123: "F12",
  144: "NumLock",
  145: "Scroll Lock",
  186: ":",
  187: "=",
  188: "Comma",
  189: "Dash",
  190: "Period",
  191: "Forward Slash",
  192: "Grave Accent",
  219: "Open Bracket",
  220: "Back Slash",
  221: "Close Bracket",
  222: "Single Quote",
};

export const leaderboardAccounts = [
  {
    id: "syd100",
    fname: "SHUBHAM",
    lname: "PANDEY",
    country: "INDIA",
    score: 100,
  },
  {
    id: "ria50",
    fname: "RAJU",
    lname: "RAST0GI",
    country: "MALAYSIA",
    score: 50,
  },
  { id: "chs75", fname: "CHARLIE", lname: "PUTH", country: "USA", score: 75 },
  {
    id: "coi90",
    fname: "CHANG LE",
    lname: "SHAO",
    country: "CHINA",
    score: 90,
  },
];
export const colors = new Array(
  "#ff0000",
  "#00ff00",
  "#0000ff",
  "pink",
  "aqua",
  "yellow",
  "brown",
  "purple",
  "orange",
  "gray"
);
export const differentColors = [
  "#FF0000", // Red
  "#00FF00", // Green
  "#0000FF", // Blue
  "#FFFF00", // Yellow
  "#FF00FF", // Magenta
  "#00FFFF", // Cyan
  "#FFA500", // Orange
  "#800080", // Purple
  "#008000", // Dark Green
  "#000080", // Navy
  "#800000", // Maroon
  "#808000", // Olive
  "#008080", // Teal
  "#808080", // Gray
  "#C0C0C0", // Silver
  "#FFD700", // Gold
  "#FF4500", // Orange Red
  "#9400D3", // Dark Violet
  "#4682B4", // Steel Blue
  "#2E8B57", // Sea Green
  "#8A2BE2", // Blue Violet
  "#556B2F", // Dark Olive Green
  "#FF1493", // Deep Pink
  "#20B2AA", // Light Sea Green
];

export const fontFamilies = [
  "Arial, sans-serif",
  "Times New Roman, serif",
  "Helvetica, sans-serif",
  "Georgia, serif",
  "Courier New, monospace",
  "Verdana, sans-serif",
  "Arial Black, sans-serif",
  "Impact, sans-serif",
  "Comic Sans MS, cursive",
  "Trebuchet MS, sans-serif",
  "Palatino Linotype, Book Antiqua, Palatino, serif",
  "Lucida Console, Monaco, monospace",
  "Lucida Sans Unicode, Lucida Grande, sans-serif",
  "Garamond, Baskerville, Baskerville Old Face, Hoefler Text, Times, serif",
  "Century Gothic, sans-serif",
  "Bookman Old Style, serif",
  "Franklin Gothic Medium, Arial, sans-serif",
  "Consolas, monospace",
  "Cambria, Georgia, serif",
  "Rockwell, serif",
];
