/* Day 5 Countries Array
export const countries = [
  "Albania",
  "Bolivia",
  "Canada",
  "Denmark",
  "Ethiopia",
  "Finland",
  "Germany",
  "Hungary",
  "Ireland",
  "Japan",
  "Kenya",
];
*/
export const webTechs = [
  "HTML",
  "CSS",
  "JavaScript",
  "React",
  "Redux",
  "Node",
  "MongoDB",
];
export const countries = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Cape Verde",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Colombi",
  "Comoros",
  "Congo (Brazzaville)",
  "Congo",
  "Costa Rica",
  "Cote d'Ivoire",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czech Republic",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "East Timor (Timor Timur)",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "Gambia, The",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Korea, North",
  "Korea, South",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Macedonia",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia and Montenegro",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Swaziland",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Togo",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Vatican City",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe",
];
export const colorsHex = [
  "#ff0000",
  "#0000ff",
  "#00ff00",
  "#ffff00",
  "#ffa500",
  "#800080",
  "#ffc0cb",
  "#00ffff",
  "#ff00ff",
  "#008080",
  "#00ff00",
  "#800000",
  "#000080",
  "#808000",
  "#c0c0c0",
  "#ffffff",
  "#a52a2a",
  "#808080",
  "#4b0082",
  "#40e0d0",
  "#fa8072",
  "#87ceeb",
  "#ee82ee",
  "#ff7f50",
  "#da70d6",
  "#ffd700",
  "#f0e68c",
  "#fffff0",
  "#d2b48c",
  "#dc143c",
  "#7fffd4",
  "#e6e6fa",
  "#dda0dd",
  "#7fff00",
  "#ff6347",
  "#faf0e6",
  "#cd853f",
  "#d8bfd8",
  "#6495ed",
  "#b22222",
  "#2f4f4f",
  "#bdb76b",
  // Add more colors as needed
];
export const monthNames = [
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December",
];
export const ayKeywords = [
  "#HTML",
  "#HTML5",
  "#CSS",
  "#CSS",
  "#JS",
  "#JavaScript",
  "#ES6",
  "Promise",
  "#async await",
  "Database",
  "#React",
  "#React Hooks",
  "#Context API",
  "#React Router",
  "#Redux",
  "#Node",
  "#MongoDB",
  "#SQL",
  "#API",
  "#DOM",
  "#data science",
  "#MERN",
  "#Python",
  "#Flask",
  "#Statistics",
  "#Linear Algebra",
  "#Numpy",
  "#Pandas",
  "#Scipy",
  "#Scikit-learn",
  "#Visualization",
  "#D3.js",
];
export const aySkills = [
  "Web Development",
  "Data Analysis",
  "Data Visualization",
  "Programming",
  "Databases",
  "Developing API",
];
export const ayQualifications = [
  "MSc. Computer Science Ongoing",
  "Bsc. Information and Communication Eng.",
  "MSc. Food Technology",
  "BSc. Food Technology",
];
export const ayTitles = [
  "Educator",
  "Programmer",
  "Developer",
  "Motivator",
  "Content Creator",
];
